name: Test Email HTML

on:
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send test email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          to: chenczn3528@163.com
          from: ${{ secrets.EMAIL_USERNAME }}
          subject: HTML 渲染测试
          html_body: |
            <h2>这是一封 HTML 邮件</h2>
            <p style="color: green;">+ 新增内容</p>
            <p style="color: red;">- 删除内容</p>
