name: Update Songs JSON

on:
  schedule:
    - cron: '0 6 * * *'  # 每天 UTC 时间 1:00 运行
  workflow_dispatch:      # 也可以手动触发

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

      - name: Run the crawler
        run: python src/update_songs.py

      # 检查是否有文件变动
      - name: Check for meaningful changes in songs files
        id: check
        run: |
          if git diff --quiet src/assets/songs_list.json src/assets/songs.json; then
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          else
            ADDED=$(git diff --numstat src/assets/songs_list.json src/assets/songs.json | awk '{added+=$1} END {print added}')
            REMOVED=$(git diff --numstat src/assets/songs_list.json src/assets/songs.json | awk '{removed+=$2} END {print removed}')
            echo "ADDED=$ADDED, REMOVED=$REMOVED"  # 可选调试输出

            if [ "$ADDED" -gt "$REMOVED" ]; then
              echo "Meaningful change detected: +$ADDED > -$REMOVED"
              echo "changes_detected=true" >> "$GITHUB_OUTPUT"
            else
              echo "Change rejected: +$ADDED <= -$REMOVED"
              echo "changes_detected=false" >> "$GITHUB_OUTPUT"
            fi
          fi

      # 提取文件差异并高亮显示
      - name: Extract and highlight diff of songs.json and songs_list.json
        if: steps.check.outputs.changes_detected == 'true'
        id: diff
        run: |
          DIFF_HTML=$(mktemp)

          git diff src/assets/songs_list.json src/assets/songs.json | \
          sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' | \
          sed -E \
            -e '/^\+/ s|^\+|<div style="background-color:#e6ffed;color:#22863a;"><code>+|' \
            -e '/^\-/ s|^\-|<div style="background-color:#ffeef0;color:#b31d28;"><code>-|' \
            -e '/^ / s|^ |<div><code> |' \
            -e 's|$|</code></div>|' \
          > "$DIFF_HTML"

          {
            echo "diff_html<<EOF"
            cat "$DIFF_HTML"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      # 提交变更
      - name: Commit updated files
        if: steps.check.outputs.changes_detected == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/assets/songs_list.json src/assets/songs.json
          DATE=$(date +'%Y-%m-%d')
          git commit -m "chore: update songs data on $DATE"
          git pull --rebase
          git push

      # 发送邮件通知（文件有变动时）
      - name: Send email if songs.json or songs_list.json changed
        if: steps.check.outputs.changes_detected == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: BeyondWorld Songs Updated
          to: chenczn3528@163.com
          from: ${{ secrets.EMAIL_USERNAME }}
          html_body: |
            <h3>songs.json 和 songs_list.json 已更新</h3>
            <p>以下是更新内容：</p>
            <div style="background:#f6f8fa;padding:16px;border-radius:6px;overflow:auto;font-family:monospace;">
            ${{ steps.diff.outputs.diff_html }}
            </div>