name: Update Cards JSON

on:
  schedule:
    - cron: '0 0 * * *'  # 每天00:00执行
  workflow_dispatch:

jobs:
  update_cards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: |
          python src/update_cards.py

      - name: Check for changes
        id: check
        run: |
          if git diff --quiet src/assets/cards.json; then
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          else
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Extract and highlight diff of cards.json
        if: steps.check.outputs.changes_detected == 'true'
        id: diff
        run: |
          echo "diff_html<<EOF" >> "$GITHUB_OUTPUT"
          git diff src/assets/cards.json \
          | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g' \
          | sed -e 's/^+/<span style="color:#22863a;">&<\/span>/g' \
                -e 's/^-/<span style="color:#b31d28;">&<\/span>/g' \
          >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Commit updated cards.json
        if: steps.check.outputs.changes_detected == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add src/assets/cards.json
          git commit -m "Update cards.json"
          git push

      - name: Send email if cards.json changed
        if: steps.check.outputs.changes_detected == 'true'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Cards JSON Updated
          to: chenczn3528@163.com
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/html
          body: |
            <h3>cards.json 已更新</h3>
            <p>以下是更新内容：</p>
            <pre style="background:#f6f8fa;padding:16px;border-radius:6px;overflow:auto;font-family:monospace;">${{ steps.diff.outputs.diff_html }}
            </pre>