name: Update Cards JSON

on:
  schedule:
    - cron: '0 0 * * *'  # 每天的00:00执行，使用Cron语法
  workflow_dispatch:  # 允许手动触发

jobs:
  update_cards:
    runs-on: ubuntu-latest  # 使用Ubuntu最新版本的运行环境

    steps:
      # Checkout 项目代码
      - name: Checkout repository
        uses: actions/checkout@v2

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 使用Python 3.x

      # 安装依赖（假设你有一个 requirements.txt 文件）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 运行 Python 脚本
      - name: Run update script
        run: |
          python src/update_cards.py  # 替换为你的脚本名称

      # 将更新后的 cards.json 文件提交到 GitHub
      - name: Commit updated cards.json
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/cards.json
          git commit -m "Update cards.json"
          git push

